/* eslint-disable no-unused-vars */

function getComputedStyleProperties(computedStyle) {
  return {
    fontFamily: computedStyle.fontFamily,
    color: computedStyle.color,
    fontSize: computedStyle.fontSize,
    lineHeight: computedStyle.lineHeight,
    fontWeight: computedStyle.fontWeight,
    fontStyle: computedStyle.fontStyle,
    fontVariant: computedStyle.fontVariant,
    textDecoration: computedStyle.textDecoration,
    textAlign: computedStyle.textAlign,
    textIndent: computedStyle.textIndent,
    textTransform: computedStyle.textTransform,
    wordSpacing: computedStyle.wordSpacing,
    letterSpacing: computedStyle.letterSpacing,
    wordWrap: computedStyle.wordWrap,
    whiteSpace: computedStyle.whiteSpace,
    verticalAlign: computedStyle.verticalAlign,
    backgroundColor: computedStyle.backgroundColor,
    backgroundImage: computedStyle.backgroundImage,
    backgroundPosition: computedStyle.backgroundPosition,
    backgroundSize: computedStyle.backgroundSize,
    backgroundBlendMode: computedStyle.backgroundBlendMode,
    backgroundAttachment: computedStyle.backgroundAttachment,
    paddingTop: computedStyle.paddingTop,
    paddingRight: computedStyle.paddingRight,
    paddingBottom: computedStyle.paddingBottom,
    paddingLeft: computedStyle.paddingLeft,
    marginTop: computedStyle.marginTop,
    marginRight: computedStyle.marginRight,
    marginBottom: computedStyle.marginBottom,
    marginLeft: computedStyle.marginLeft,
    width: computedStyle.width,
    height: computedStyle.height,
    maxWidth: computedStyle.maxWidth,
    maxHeight: computedStyle.maxHeight,
    minWidth: computedStyle.minWidth,
    minHeight: computedStyle.minHeight,
  };
}
